export const ErrorCodes = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  GITHUB_USER_NOT_FOUND: "GITHUB_USER_NOT_FOUND",
  GITHUB_RATE_LIMITED: "GITHUB_RATE_LIMITED",
  GITHUB_API_ERROR: "GITHUB_API_ERROR",
  DATABASE_ERROR: "DATABASE_ERROR",
  ANALYSIS_NOT_FOUND: "ANALYSIS_NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
